# 区分错误和异常：
> 错误是指可能出现问题的地方出现了问题，情况在意料之中  
> 异常是不该出现问题的地方出现了问题，情况在意料之外  
> 错误是业务过程的一部分，而异常不是  
> 错误和异常从Go机制上讲，就是error和panic的区别  
---

# 错误处理：
## error类型：
> error类型是一个go语言的内建接口类型  
> 其使用方法通常是：  
> 1. 在函数结果列表的最后声明该类型结果
> 2. 在调用该函数时，判断该值是否为nil，若不为nil就进入错误处理流程
## 自定义错误：
```go
func f(a, b int) (rst int, err error){
    if b == 0 {
        err = errors.New("除数不能为0")
        return
    }
    rst = a/b
    return
}
```
## 错误值统一定义：
> 为了使得错误更统一规范，保证错误value统一  
> 可以在每个Go包中增加一个错误对象定义文件
> 在该文件内对错误进行统一定义
```go
// myError.go
var ERR_EOF = errors.New("EOF")
var ERR_CLOSED_PIPE = errors.New("io: read/write on closed pipe")
var ERR_NO_PROGRESS = errors.New("multiple Read calls return no data or error")
```
## 错误使用规范：
1. 当一个函数的失败原因只有一个时，不用返回error,返回bool即可
2. 若一个函数没有失败可能时，不用返回error
3. error应该放在返回值列表的最后
4. 错误处理时，当发生错误要使用defer去释放资源
5. 当可以尝试几次避免失败时，不要立即返回错误，而应该重试几次
---

# 异常处理：
## 简介：
> 意料之外的程序异常被叫做panic  
> 当panic被抛出后，若未在程序里添加任何保护措施  
> 程序所在的那个进程就会在打印出panic详情后终止运行  
## 从panic被引发到程序终止运行的大致过程:
1. 某行代码引发了panic
2. 初试panic详情被建立起来
3. 程序控制权从此行代码转移至调用其所属函数的那行代码上  
控制权一级级沿着调用栈反向传播至顶端(最外层函数那里)
4. 程序崩溃并终止运行
5. panic详情逐渐完善，并在程序终止前被打印出来
## recover捕获异常：
> 当一个函数抛出panic，该函数可以在defer中通过recover捕获该异常信息  
> 这样程序就可以跳出该函数，继续从调用该函数处的下一处继续运行  
> 而避免整个程序崩溃
## 示例：
```go
func f(s string) {
    defer func() {
        panicInfo := recover()
        // 当panicInfo不为nil时，说明有panic被捕获到(为nil说明未捕获到panic)
        if panicInfo != nil {
            fmt.Printf("出现异常，异常为: %v\n", err)
        }
    }()
    if s == "p" {
        // 自定义panic
        // panic的value可以为任何类型，但推荐是一个error类型
        panic(errors.New("自定义错误"))
    }
    fmt.Println(s)
}

func main() {
    f("11111")
    f("p")
    // 当程序panic被捕获后跳出f("p")函数，继续执行f("22222")
    f("22222")
}
```